name: CD

on:
  workflow_run:
    workflows: ["CI devops 2025"]
    types:
      - completed

jobs:
  build-and-push-docker-image:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Auto-increment version from pom.xml
        id: versioning
        working-directory: ./simple-api
        run: |
          FILE=pom.xml

          # Get current version from Maven
          CURRENT_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo "Current version: $CURRENT_VERSION"

          BASE_VERSION=$(echo $CURRENT_VERSION | sed 's/-SNAPSHOT//')
          MAJOR=$(echo $BASE_VERSION | cut -d. -f1)
          MINOR=$(echo $BASE_VERSION | cut -d. -f2)
          PATCH=$(echo $BASE_VERSION | cut -d. -f3)

          NEXT_PATCH=$((PATCH + 1))
          NEW_VERSION="$MAJOR.$MINOR.$NEXT_PATCH-SNAPSHOT"

          echo "New version: $NEW_VERSION"

          # Update in pom.xml
          sed -i "s/<version>$CURRENT_VERSION<\/version>/<version>$NEW_VERSION<\/version>/" $FILE

          echo "IMAGE_TAG=$NEW_VERSION" >> $GITHUB_ENV

      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login --username ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Build and push backend image
        uses: docker/build-push-action@v6
        with:
          context: ./simple-api
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/tp2gitaction-simple-api:${{ env.IMAGE_TAG }}
            ${{ secrets.DOCKERHUB_USERNAME }}/tp2gitaction-simple-api:latest
          push: true

      - name: Build and push database image
        uses: docker/build-push-action@v6
        with:
          context: ./database
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/tp2gitaction-database:${{ env.IMAGE_TAG }}
            ${{ secrets.DOCKERHUB_USERNAME }}/tp2gitaction-database:latest
          push: true

      - name: Build and push httpd image
        uses: docker/build-push-action@v6
        with:
          context: ./http-server
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/tp2gitaction-httpd:${{ env.IMAGE_TAG }}
            ${{ secrets.DOCKERHUB_USERNAME }}/tp2gitaction-httpd:latest
          push: true
