name: CD

on:
  workflow_run:
    workflows: ["CI devops 2025"]
    types:
      - completed

jobs:
  build-and-push-docker-image:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set version from pom.xml
        id: version
        run: |
          sudo apt-get update && sudo apt-get install -y libxml2-utils
          VERSION=$(xmllint --xpath "string(//project/version)" simple-api/pom.xml)
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT

      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login --username ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Build and push backend
        uses: docker/build-push-action@v6
        with:
          context: ./simple-api
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/tp2gitaction-simple-api:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/tp2gitaction-simple-api:${{ steps.version.outputs.VERSION }}
            ${{ secrets.DOCKERHUB_USERNAME }}/tp2gitaction-simple-api:${{ github.run_number }}
          push: true

      - name: Build and push database
        uses: docker/build-push-action@v6
        with:
          context: ./database
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/tp2gitaction-database:${{ steps.version.outputs.VERSION }}
            ${{ secrets.DOCKERHUB_USERNAME }}/tp2gitaction-database:${{ github.run_number }}
          push: true

      - name: Build and push httpd
        uses: docker/build-push-action@v6
        with:
          context: ./http-server
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/tp2gitaction-httpd:${{ steps.version.outputs.VERSION }}
            ${{ secrets.DOCKERHUB_USERNAME }}/tp2gitaction-httpd:${{ github.run_number }}
          push: true
