name: CD

on:
  workflow_run:
    workflows: ["CI devops 2025"]
    types:
      - completed

permissions:
  contents: write  # ✅ Autorise le push vers le repo

jobs:
  update-version:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set new version in pom.xml
        run: |
          VERSION="0.0.${{ github.run_number }}-SNAPSHOT"
          echo "Updating version to $VERSION"
          sed -i "0,/<version>.*<\/version>/s//<version>${VERSION}<\/version>/" simple-api/pom.xml

      - name: Commit updated pom.xml
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git add simple-api/pom.xml
          git commit -m "Update version to 0.0.${{ github.run_number }}-SNAPSHOT"
          git push

  build-and-push-docker-image:
    needs: update-version
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Extract version from pom.xml
        id: version
        run: |
          sudo apt-get update && sudo apt-get install -y libxml2-utils
          VERSION=$(xmllint --xpath "string(//project/version)" simple-api/pom.xml)
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT

      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login --username ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Build and push backend
        uses: docker/build-push-action@v6
        with:
          context: ./simple-api
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/tp2gitaction-simple-api:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/tp2gitaction-simple-api:${{ steps.version.outputs.VERSION }}
          push: true

      - name: Build and push database
        uses: docker/build-push-action@v6
        with:
          context: ./database
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/tp2gitaction-database:${{ steps.version.outputs.VERSION }}
          push: true

      - name: Build and push httpd
        uses: docker/build-push-action@v6
        with:
          context: ./http-server
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/tp2gitaction-httpd:${{ steps.version.outputs.VERSION }}
          push: true
