name: CI devops 2025

# Déclencheur : à chaque push ou PR sur les branches main et develop
on:
  push:
    branches:
      - main
      - develop
  pull_request:

jobs:
  test-backend:
    runs-on: ubuntu-24.04

    steps:
      # Étape 1 : Récupère le code depuis le dépôt GitHub
      - name: Checkout repository
        uses: actions/checkout@v4

      # Étape 2 : Installe Java 21 via Temurin
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      # Étape 3 : Build + Tests (unitaires et d'intégration)
      - name: Build and test with Maven
        run: mvn clean verify --file ./simple-api/pom.xml
