name: CI devops 2025

# Déclencheur : à chaque push ou PR sur les branches main et develop
on:
  push:
    branches:
      - main
      - develop
  pull_request:

jobs:
  test-backend:
    runs-on: ubuntu-24.04

    steps:
      # Étape 1 : Récupère le code depuis le dépôt GitHub
      - name: Checkout repository
        uses: actions/checkout@v4

      # Étape 2 : Installe Java 21 via Temurin
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      # Étape 3 : Build + Tests (unitaires et d'intégration)
      - name: Build and test with Maven
        run: mvn clean verify --file ./simple-api/pom.xml

        
  build-and-push-docker-image:
    needs: test-backend
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login --username ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Build and push backend
        uses: docker/build-push-action@v6
        with:
          context: ./apisimple
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-simple-api:latest
          push: true

      - name: Build and push database
        uses: docker/build-push-action@v6
        with:
          context: ./database
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-database:latest
          push: true

      - name: Build and push httpd
        uses: docker/build-push-action@v6
        with:
          context: ./http-server
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-httpd:latest
          push: true